// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nba.Data.Models;

[Table("Game")]
[Index("AwayTeamId", Name = "IX_Game_AwayTeamId")]
[Index("Date", Name = "IX_Game_Date")]
[Index("HomeTeamId", Name = "IX_Game_HomeTeamId")]
public partial class Game : HasModifiedDates
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int SeasonId { get; set; }

    public int HomeTeamId { get; set; }

    public int AwayTeamId { get; set; }

    public int? VenueId { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    public int? HomeTeamScore { get; set; }

    public int? AwayTeamScore { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SportRadarId { get; set; }

    [Required]
    public Guid SportRadarGuid { get; set; }

    [ForeignKey("AwayTeamId")]
    [InverseProperty("GameAwayTeams")]
    public virtual Team AwayTeam { get; set; }

    [ForeignKey("HomeTeamId")]
    [InverseProperty("GameHomeTeams")]
    public virtual Team HomeTeam { get; set; }

    [ForeignKey("VenueId")]
    [InverseProperty("Games")]
    public virtual Venue Venue { get; set; }
}