// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nba.Data.Models;

[Table("Team")]
public partial class Team : HasModifiedDates
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(3)]
    public string Alias { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SportRadarId { get; set; }

    [Required]
    public Guid SportRadarGuid { get; set; }

    [InverseProperty("AwayTeam")]
    public virtual ICollection<Game> GameAwayTeams { get; set; } = new List<Game>();

    [InverseProperty("HomeTeam")]
    public virtual ICollection<Game> GameHomeTeams { get; set; } = new List<Game>();
}