// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nba.Data.Models;

[Table("Venue")]
public partial class Venue : HasModifiedDates
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string City { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    [StringLength(50)]
    public string Zip { get; set; }

    [Required]
    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(50)]
    public string Latitude { get; set; }

    [StringLength(50)]
    public string Longitude { get; set; }

    [StringLength(50)]
    public string TimeZone { get; set; }

    public int? Capacity { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SportRadarId { get; set; }

    [Required]
    public Guid SportRadarGuid { get; set; }

    [InverseProperty("Venue")]
    public virtual ICollection<Game> Games { get; set; } = new List<Game>();
}