/*
Deployment script for Nba

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/


SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Nba')
BEGIN
    CREATE DATABASE Nba;
END
GO

Use Nba;


PRINT N'Creating Table [dbo].[Game]...';


GO
CREATE TABLE [dbo].[Game] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [Date]           DATETIME         NOT NULL,
    [SeasonId]       INT              NOT NULL,
    [HomeTeamId]     INT              NOT NULL,
    [AwayTeamId]     INT              NOT NULL,
    [VenueId]        INT              NULL,
    [Status]         VARCHAR (50)     NOT NULL,
    [HomeTeamScore]  INT              NULL,
    [AwayTeamScore]  INT              NULL,
    [SportRadarId]   VARCHAR (50)     NULL,
    [SportRadarGuid] UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]    DATETIME         NOT NULL,
    [DateUpdated]    DATETIME         NOT NULL,
    CONSTRAINT [PK_Game_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Game].[IX_Game_Date]...';


GO
CREATE NONCLUSTERED INDEX [IX_Game_Date]
    ON [dbo].[Game]([Date] ASC);


GO
PRINT N'Creating Index [dbo].[Game].[IX_Game_HomeTeamId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Game_HomeTeamId]
    ON [dbo].[Game]([HomeTeamId] ASC);


GO
PRINT N'Creating Index [dbo].[Game].[IX_Game_AwayTeamId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Game_AwayTeamId]
    ON [dbo].[Game]([AwayTeamId] ASC);


GO
PRINT N'Creating Table [dbo].[Team]...';


GO
CREATE TABLE [dbo].[Team] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [Name]           NVARCHAR (50)    NOT NULL,
    [Alias]          NVARCHAR (3)     NOT NULL,
    [SportRadarId]   VARCHAR (50)     NULL,
    [SportRadarGuid] UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]    DATETIME         NOT NULL,
    [DateUpdated]    DATETIME         NOT NULL,
    CONSTRAINT [PK_Team_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Venue]...';


GO
CREATE TABLE [dbo].[Venue] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [Name]           NVARCHAR (50)    NOT NULL,
    [Address]        NVARCHAR (100)   NULL,
    [City]           NVARCHAR (50)    NOT NULL,
    [State]          NVARCHAR (50)    NULL,
    [Zip]            NVARCHAR (50)    NULL,
    [Country]        NVARCHAR (50)    NOT NULL,
    [Latitude]       NVARCHAR (50)    NULL,
    [Longitude]      NVARCHAR (50)    NULL,
    [TimeZone]       NVARCHAR (50)    NULL,
    [Capacity]       INT              NULL,
    [SportRadarId]   VARCHAR (50)     NULL,
    [SportRadarGuid] UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]    DATETIME         NOT NULL,
    [DateUpdated]    DATETIME         NOT NULL,
    CONSTRAINT [PK_Venue_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Game_Team_Home]...';


GO
ALTER TABLE [dbo].[Game] WITH NOCHECK
    ADD CONSTRAINT [FK_Game_Team_Home] FOREIGN KEY ([HomeTeamId]) REFERENCES [dbo].[Team] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Game_Team_Away]...';


GO
ALTER TABLE [dbo].[Game] WITH NOCHECK
    ADD CONSTRAINT [FK_Game_Team_Away] FOREIGN KEY ([AwayTeamId]) REFERENCES [dbo].[Team] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Game_Venue]...';


GO
ALTER TABLE [dbo].[Game] WITH NOCHECK
    ADD CONSTRAINT [FK_Game_Venue] FOREIGN KEY ([VenueId]) REFERENCES [dbo].[Venue] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [dbo].[Game] WITH CHECK CHECK CONSTRAINT [FK_Game_Team_Home];

ALTER TABLE [dbo].[Game] WITH CHECK CHECK CONSTRAINT [FK_Game_Team_Away];

ALTER TABLE [dbo].[Game] WITH CHECK CHECK CONSTRAINT [FK_Game_Venue];


GO
PRINT N'Update complete.';


GO
